CREATE TABLE POST
(
    ID      NUMBER(19)       NOT NULL,
    TITLE   VARCHAR2(255)    NOT NULL,
    USER_ID NUMBER(19)       NOT NULL,
    BODY    CLOB NOT NULL,
    CONSTRAINT PK_POST PRIMARY KEY (ID)
);