CREATE TABLE POSTS
(
    ID      NUMBER(19)       NOT NULL,
    TITLE   VARCHAR2(255)    NOT NULL,
    USER_ID NUMBER(19)       NOT NULL,
    BODY    CLOB NOT NULL,
    CONSTRAINT PK_POST PRIMARY KEY (ID)
);

create index IDX_POSTS_USER_ID on POSTS (USER_ID);




CREATE USER xyz IDENTIFIED BY "adm"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO xyz;

GRANT
    CREATE TABLE,
    CREATE VIEW,
    CREATE SEQUENCE,
    CREATE PROCEDURE,
    CREATE TRIGGER,
    CREATE TYPE
    TO xyz;

GRANT
    SELECT ANY TABLE,
    INSERT ANY TABLE,
    UPDATE ANY TABLE,
    DELETE ANY TABLE
    TO xyz;

GRANT CREATE SYNONYM TO xyz;

